[package]
name = "fizzyhex/revy"
description = "toolkit"
version = "0.7.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = false
include = ["default.project.json", "dist"]
exclude = [
    "dev.project.json",
    ".github",
	".gitattributes",
	".gitignore",
    ".luaurc",
    ".copilotignore",
	"README.md",
    "scripts",
    "src",
    "sourcemap.json",
    "scripts",
    "aftman.toml",
    "selene.toml",
    "selene_definitions.yml",
    "game"
]

[dependencies]